# Generated by Django 5.0 on 2024-01-08 06:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(db_default=models.Value(datetime.datetime(2023, 1, 31, 13, 35, tzinfo=datetime.timezone.utc))),
        ),
    ]
